### ISSUE TITLE
Predis adapter

### ISSUE THREAD

**Issue by jimbojsb** [tedious/Stash#133]
I have written a Predis adapter in place of the included adapter (we have Predis and phpiredis in our ecosystem. I saw there is an open ticket about something that would allow this to be more pluggable but it's quite old. I'd be happy to contribute the adapter if that is needed/wanted.

**Comment by alexbowers-tecmark** [comment]
@jimbojsb Do you have this code still? Would be useful. Thanks

**Comment by jimbojsb** [comment]
Was never able to get it fully working. I'll see if I can dig it up.

On Thu, Apr 9, 2015 at 9:23 AM, alexbowers-tecmark <notifications@github.com

**Comment by alexbowers-tecmark** [comment]
That'd be great. if you publish it, I may get the time to work on it too :)
