### ISSUE TITLE
FileSystem Driver Won't Clear for Relative Paths

### ISSUE THREAD

**Issue by jonmchan** [tedious/Stash#143]
When defining relative paths to the FileSystem driver, the clear() functionality won't work because https://github.com/tedivm/Stash/blob/master/src/Stash/Utilities.php#L124 deleteRecursive function throws an exception: 

```throw new RuntimeException('deleteRecursive function requires an absolute path.');```

Is relative paths not supported or not recommended for use for the FileSystem driver? If it isn't supported, can we have this added to the documentation. (Much apologies if I missed it.)

What is the issue or concern here for making the Utility only support absolute paths? If necessary, can we run the path through ```realpath()``` in FileSystem::clear() before passing it to deleteRecursive?

**Comment by mac-u** [comment]
Yes, error is not solved with dev-master.

**Comment by mac-u** [comment]
Problem solved. Wrong cache path used.
