### ISSUE TITLE
Stampede Protection Questions

### ISSUE THREAD

**Issue by connerbw** [tedious/Stash#203]
Hi,

I'm using Stash v0.12.2, installed using Composer, configured using the Redis driver.

It is unclear to me if [Stampede Protection](http://www.stashphp.com/Invalidation.html) is working as expected. I have a couple questions. If this is not an appropriate support forum, please redirect me.

 1. Does `$item->get(\Stash\Invalidation::OLD);`  work with`$item->clear()`? If not, what is the best way to manually invalidate an $item?

 2. My Stampede Protection tests involved putting `sleep()` in the code and reloading a bunch of browser tabs. In all cases `$item->isMiss()` was true. That is, all tabs seem to be fighting with each other and `$item->lock()` was ignored. Obviously this isn't the best testing, but I did put in a couple hours of trying, and could not get Stash to work as I expected. Can you direct me to a test case where Stamped Protection using `\Stash\Invalidation::OLD` works, specifically with Redis?

Thank you for your time.

**Comment by tedivm** [comment]
1. Clearing always clears regardless of invalidation method. If you run clear whatever item you're working with will be removed from all connected caching systems.

2. I'd have to see your code to see what's up, but I recommend using the "PRECOMPUTE" invalidation method instead of OLD.

**Comment by connerbw** [comment]
Ok, thanks!
