### ISSUE TITLE
Uncaught exception 'RedisException' with message 'Connection closed'

### ISSUE THREAD

**Issue by connerbw** [tedious/Stash#205]
I upgraded to Stash 0.12.3 today.

I'm now seeing this error (where I was previously not)

```
<b>Fatal error</b>:  Uncaught exception 'RedisException' with message 'Connection closed' in vendor/tedivm/stash/src/Stash/Driver/Redis.php:247
Stack trace:
#0 vendor/tedivm/stash/src/Stash/Driver/Redis.php(247): Redis-&gt;incr('7eb53cc3342e5d2...')
#1 vendor/tedivm/stash/src/Stash/Item.php(591): Stash\Driver\Redis-&gt;clear(Array)
#2 [internal function]: Stash\Item-&gt;__destruct()
#3 {main}
  thrown in <b>vendor/tedivm/stash/src/Stash/Driver/Redis.php</b> on line <b>247</b><br />
```

**Comment by connerbw** [comment]
Invalid. Sorry.

That being said, I am using Stash in a [Slim Framework Middleware Class](http://docs.slimframework.com/#Middleware-Overview) to cache GET output.

The problem, when using the Middleware pattern, was:

```
        if ($item->isMiss()) {
            // Cache miss, continue on to generate the page
            $item->lock();
            $this->next->call();
            if (200 == $this->app->response()->getStatus()) {
                // Cache result for future look up
                $item->set($body = $this->app->response()->getBody());
                $this->app->request()->headers()->set('IF_MODIFIED_SINCE', null);
                $this->app->lastModified($item->getCreation()->getTimestamp());
            } else {
                // Something went wrong
                // I NEED TO DO SOMETHING WITH ITEM HERE OR STASH THROWS AN EXCEPTION
           }
```

I have opted to do `$item->set(null, 0);` but it would have been nice to have `$item->unlock()` or something similar that allows me abort my lock.

Thanks

**Comment by tedivm** [comment]
The lock should get cleared when the item is destructed.

**Comment by connerbw** [comment]
Hi @tedivm, thanks for the reply.

> The lock should get cleared when the item is destructed.

Right, but it doesn't.

In my Slim code, If I instead do: 

```
 if ($item->isMiss()) {
            // Cache miss, continue on to generate the page
            $item->lock();
            $this->next->call();
            if (200 == $this->app->response()->getStatus()) {
                // Cache result for future look up
                $item->set($body = $this->app->response()->getBody());
                $this->app->request()->headers()->set('IF_MODIFIED_SINCE', null);
                $this->app->lastModified($item->getCreation()->getTimestamp());
            } else {
                // *** PROBLEM AREA ***
                unset($item)
           }
```

This "destroys" the item, so "The lock should get cleared"

The problem is that in PHP I cannot  explicitly destroy an object. The item will stay there until PHP runs out of memory and decides its time for the item to be garbage collected.

Furthermore, I did not explicitly open, (or close) the Redis connection. Rather Stash abstracts this away from me. I cannot try/catch a __destruct() exception because it is out of scope from my code snippet.

Please see attached Exception.png

![exception](https://cloud.githubusercontent.com/assets/812192/5837403/f0cfe9cc-a14c-11e4-82dd-ed848f6181e7.png)

Thank you for your time. Best regards,
