### ISSUE TITLE
Redis clear method

### ISSUE THREAD

**Issue by ivanskins** [tedious/Stash#207]
I save cache in Redis with this code:

$item = $pool->getItem('34', 'templates', 'page1');
$data = $item->get();
if($item->isMiss()) {
...
}
$item->set($data);

But then I execute:
$pool->getItem('34', 'templates')->clear();

And NO clearing was executed, may be I do simething wrong?

**Comment by Nakard** [comment]
What do you mean exactly by "no clearing executed"? Does 
```php
$pool->getItem('34', 'templates', 'page1')->isMiss()
```
return false after using clear()?

Or do you mean that there is still something on the Redis server? If that's the issue, then look at this [issue](https://github.com/tedious/Stash/issues/201)

**Comment by ivanskins** [comment]
Sorry ... "no clearing executed" means that key "'34/templates/page1" was not deleted from Redis

**Comment by tedivm** [comment]
So if you retrieve ""34/templates/page1" again you get the value back and isMiss returns false, even though you cleared it? Can you show me a full script executing this?

**Comment by ivanskins** [comment]
the problem is not in isMiss method. The problem is in the following:
1) I created cache "34/templates/page1"
2) I created cache "34/templates/page2"
3) I want to clear all children of "34/templates"
4) I call "$pool->getItem('34', 'templates')->clear();"
5) BUT "34/templates/page1" and "34/templates/page2" are exist and were not deleted

**Comment by tedivm** [comment]
Can you please answer my question? If you attempt to retrieve "34/templates/page1" and "34/templates/page2" from the caching system after clearing them what happens?

**Comment by ivanskins** [comment]
I will try at the moment, one minute)

**Comment by ivanskins** [comment]
Yes, result of "var_dump($item->isMiss())" is "true", it's correct.
But why the key exists in Redis? I think that key removing from Redis is a good idea.

**Comment by Roquie** [comment]
Also not work with FileSystem driver... method `$this->makePath($key = null)` returned path to folder with `.php` extension.
![2015-04-17 1 31 39](https://cloud.githubusercontent.com/assets/3214290/7192676/546e68dc-e4a0-11e4-923d-baf4c806014c.png)
![2015-04-17 1 32 00](https://cloud.githubusercontent.com/assets/3214290/7192678/585c9fcc-e4a0-11e4-827e-ccc757d330c8.png)

**Comment by tedivm** [comment]
Sorry to disappear from the conversation.

In order to get hierarchal caching to work Stash uses an index system that relies on numbered keys. When things are purged those keys are incremented and the stale items get orphaned. The downside to this method is that it isn't easy to clear those purged items from inside Stash itself, but the two systems we do this with (Redis and Memcache) will handle that automatically using the "Least Recently Used" expiration method.

**Comment by tedivm** [comment]
Closing this out as it's expected behavior.
