### ISSUE TITLE
Flush does not work

### ISSUE THREAD

**Issue by pyrsmk** [tedious/Stash#208]
Hi!

It seems that `$pool->flush()` does not work at all for my case. It runs without error but when I'm accessing my website I see that the cache is still there. I debugged a bit, and all the cache is not considered as missed, then nothing is regenerated.

Maybe a problem with rights on the hosting service? But then, why `$pool->flush()` does not throw any error?

**Comment by tedivm** [comment]
Flush only removes stale items- it's a cleanup operation. You may want to look at clear instead of flush, as that's probably what you're looking for.

**Comment by pyrsmk** [comment]
But according to your API documentation, `flush()` does the following : 

```
The flush function completely empties all items associated with the Pool. After calling this every Item will be considered a miss and will have to be regenerated.
```

And the `clear()` method is only accessible on items. I just want to clear all the cache. The `getItemIterator()` does not retrieve all the items. How can I do that?

**Comment by Nakard** [comment]
You can execute the following code to clear all the cache 
``` php
$pool->getDriver()->clear()
```

**Comment by pyrsmk** [comment]
Thanks a lot, it works like a charm ;)
