### ISSUE TITLE
Implement a max cache size for FileSystem driver

### ISSUE THREAD

**Issue by stevevance** [tedious/Stash#210]
There should be an option for the FileSystem driver that implements a maximum disk size that can be used. When the maximum is reached Stash starts purging old cached items.

**Comment by tedivm** [comment]
This can lead to problems. If we revoke the oldest items first then we risk the chance of revoking something that is really expensive to reproduce. This is also the case with removing the largest items. Something like a least recently used method would work but means we need to record a last usage for items, which would really increase overhead by adding a lot of writes into a mostly read system.

The real solution to this for caches of a certain size is to switch away from the filesystem driver and over to something like memcache.
