### ISSUE TITLE
Tests not passing locally

### ISSUE THREAD

**Issue by alexbowers** [tedious/Stash#213]
I have just tried to run the tests from a fresh clone and I get these two issues.

...................SSSSSS......................SS.........SS...  63 / 182 ( 34%)
..................SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.......... 126 / 182 ( 69%)
...F................................................F.

Time: 2.76 seconds, Memory: 19.00Mb

There were 2 failures:

1) Stash\Test\ItemTest::testInvalidation
Sleep method does not oversleep.
Failed asserting that 512.77899742126465 is less than 510.

/var/www/testing/stash-core/tests/Stash/Test/AbstractItemTest.php:225

2) Stash\Test\UtilitiesTest::testDeleteRecursive
deleteRecursive cleared out the empty parent directory
Failed asserting that file "/tmp/stash/test/" does not exist.

**Comment by tedivm** [comment]
With the first issue something is causing the sleep function to take too long- is this happening consistently or sporadically? 

For issue 2 can you delete /tmp/stash and try again? If the tests were run as a different user, or root, then there may be a permissions error.

**Comment by alexbowers** [comment]
This was done via travis, so I cannot do those things.

**Comment by alexbowers** [comment]
Deleted previous message. It was factually incorrect (I said it was ran via travis, it wasn't). I will try to run this again now and see if it passes.

**Comment by alexbowers** [comment]
Can't replicate any of these issues right now. So must have been a temporary problem. Maybe I was connected as root on my vagrant machine for the tests a few days ago, who knows. I'll close and reopen if it happens again.
