### ISSUE TITLE
Warning when running composer optimize autoloader

### ISSUE THREAD

**Issue by Petah** [tedious/Stash#215]
Warning: Ambiguous class resolution, "Stash\Session\SessionHandlerInterface" was found in both "D:\home\site\repository\vendor\tedivm\stash\src\Stash\Session\SessionHandlerInterface_Legacy.php" and "D:\home\site\repository\vendor\tedivm\stash\src\Stash\Session\SessionHandlerInterface_Modern.php", the first will be used.

**Comment by tedivm** [comment]
This is a known issue, and not at all a big deal. This has to do with an issue with backwards compatibility with php5.3, and since composer is picking the legacy adapter (which is compatible with all relevant php versions) it will give the most widely usable configuration with the optimized autoloader.

**Comment by magnusnordlander** [comment]
This causes issues with Symfony when using the install mechanism recommended by StashBundle docs. 

https://github.com/symfony/HttpFoundation/blob/master/Session/Storage/NativeSessionStorage.php#L341

**Comment by magnusnordlander** [comment]
Ping @tedivm and please consider re-opening this.

**Comment by SvenRtbg** [comment]
The simple solution would be to stop supporting PHP 5.3 and raise the PHP requirement to 5.4. This should be a good thing, with PHP 5.3 not receiving any updates since about one year now.

**Comment by alexbowers** [comment]
I have to agree, requiring PHP 5.5 for forward releases makes sense now, with 5.4 support ending in 2 months as well.

http://php.net/supported-versions.php

**Comment by tedivm** [comment]
I'm willing to drop support for 5.3, which eliminates the need for the legacy class.

**Comment by Petah** [comment]
I don't see a reason not to.

**Comment by tedivm** [comment]
The newest version of Stash no longer support 5.3 and thus doesn't have this issue anymore.
