### ISSUE TITLE
Setting Modes

### ISSUE THREAD

**Issue by alexbowers** [tedious/Stash#219]
> - Normal
> - Read Only
> - Write Only
> - Disabled

This is for discussing the effect that each of these will have.

The first and last are obvious, since htey already exist. I assume that

setMode(NORMAL) will act as though nothing changed (the default value of mode).

setMode(DISABLED) will be an alias of ->disable()

The harder ones to describe would be Read Only and Write Only.

In read only, what effect should using set() have. Should it return the same as it currently does, but not store the value?

In write only, what effect should get() have. Should it return null, the value that is currently stored in teh database (effectively, a force miss)

**Comment by alexbowers** [comment]
@tedivm input please

**Comment by tedivm** [comment]
Yeah, you've got it.

**Comment by alexbowers** [comment]
The last one is still ambigious to me,

Should it return either:

1) Null; or:
2) The value currently stored in the database (and null if not exist)

**Comment by tedivm** [comment]
It should return null. Returning what's in the database requires reading, which shouldn't happen when the system is in write only mode.

**Comment by alexbowers** [comment]
This still doesn't solve the problem I had initially then, which is to have a forceMiss mode.

I need it to always write, regardless of whether there is something in the database already or not.

But it also must read the correct value at the end.

**Comment by tedivm** [comment]
Toss "forced miss" into the mix then.

**Comment by alexbowers** [comment]
@tedivm Should write only always write (IE. force miss too?)

Or should it still respect the expiration ?

**Comment by alexbowers** [comment]
@tedivm I have implemented them all, but am struggling testing the actual modes, since with all the stubs that get used etc, I don't actually understand how it is set up.

I'll submit the PR as is, and can you help me with the testing?

Thanks.

**Comment by alexbowers** [comment]
@tedivm Any input?
