### ISSUE TITLE
Update PHP requirements

### ISSUE THREAD

**Issue by alexbowers** [tedious/Stash#225]
This is just a proposal to upgrade the required version of PHP to either 5.4, 5.5 or 5.6.

My suggestion is to upgrade to 5.5; with PHP having EOL in 2 months time, there is little point upgrading the version to do it again in 5 months time.

This can be something to happen when 1.0 comes around (No idea on timeframe for that), or something to happen at 0.13. Either way, this would be something that I think should happen. Thoughts?

http://php.net/supported-versions.php

**Comment by tedivm** [comment]
I"m not going to remove 5.4 support because there are still LTS releases of operating systems on php5.4. Even though PHP isn't going to support this those specific operating systems will.

**Comment by davereid** [comment]
I think PHP 5.4 is a good minimum since I'd like to use Traits with https://github.com/tedious/Stash/pull/237

**Comment by tedivm** [comment]
Closing this out as we're no longer supporting PHP 5.3. PHP 5.4 support is still available, even though it's EOL'd next month, as it's super simple to maintain at the moment. It'll be on the chopping block soon though.
