### ISSUE TITLE
Internal Cache Mapping

### ISSUE THREAD

**Issue by alexbowers-tecmark** [tedious/Stash#228]
I'm not sure if anything like this is currently supported, or even how feasible it is to build. I'd gladly take a look into it.

The idea is rather simple, but very powerful.

Say, you have a system that has many API calls happening, but some are related in many ways; for example an ecommerce system. 

You have many caches stored, but with a developer defined array of properties to fetch as part of the API call (say, db fields), thus the individual item may not be able to be determined efficiently from the cache key. (Eg. Cache/Products/Product/[params]), there is no way to get the product that has been edited in the backend by that key, and so the current option is to wipe out ALL products (in the Cache/Products/Product) which is rather inefficient for one product that has changed. What would be better instead would be for the developer to set an internal map, which, based on the response from the API call, before ->set() is called, you can call ->map() with a secondary key. This way you could Map it to something like Map/Products/Product/unique-product-name, which can have a one to many relationship (it doesn't get overwritten, instead added to); and then on the backend or api client the developer does not need to know anything about how to get the keys generated by the parameter array, instead they simply can clear out the map for that product and it will automatically map to all of the actual caches that exist to clear them out.

If this is already possible, please point it out as the docs didn't come up with anything.

@tedivm Thanks.

**Comment by tedivm** [comment]
Can you give a code example of what this would look like?

**Comment by alexbowers-tecmark** [comment]
Do you mean an implementation, or a front-end example of it in use?
