### ISSUE TITLE
Filesystem driver does not work without call to setOptions()

### ISSUE THREAD

**Issue by tuupola** [tedious/Stash#230]
Is it intentional design decision that driver options cannot be given in constructor? There is currently some side effects such as this does not work:

```php
$pool = new Stash\Pool(
    new Stash\Driver\FileSystem()
);
```

Instead you have to make an empty call to `setOptions()`:

```php
$driver = new Stash\Driver\FileSystem();
$driver->setOptions(); 

$pool = new Stash\Pool($driver);
```

**Comment by davereid** [comment]
I just encountered this as well. I really wish that the constructors for drivers had an additional $options parameter, which then passed it through to setOptions() itself.

**Comment by tuupola** [comment]
I would like to pass options in constructor too. Although it might be intentional decision not to allow it. It is just mostly just of taste. It would be nice if at least the mandatory dummy call to `$driver->setOptions()` was removed.

**Comment by tedivm** [comment]
Closing out this ticket as #234 resolves it.

@tuupola - if you want to open a ticket about passing options to the constructor you can, but I should warn you I will have to be convinced of it.
