### ISSUE TITLE
Add OPT_PREFIX option to Redis driver

### ISSUE THREAD

**Issue by mitkola** [tedious/Stash#231]
I will suggest to add OPT_PREFIX option to Redis driver.
public function setOptions(array $options = array()) {
...
        // select database
        if (isset($options['database'])) {
            $redis->select($options['database']);
        }
        if (isset($options["opt_prefix"])) {
            $redis->setOption(\Redis::OPT_PREFIX, $options["opt_prefix"]); 
        }
...

**Comment by tedivm** [comment]
Closing as a duplicate of #202.
