### ISSUE TITLE
No way to know if the driver is persistent or temporary

### ISSUE THREAD

**Issue by davereid** [tedious/Stash#235]
It would be nice for implementations to know if the cache pool driver that has been provided is persistent or temporary. Ideally it would be nice if there was just an empty interface (`PersistentDriverInterface`) that individual drivers implemented.

**Comment by tedivm** [comment]
An interface won't work because of the Composite driver- you could load the composite driver with temporary or persistent drivers (typically a combination of both). A function (isPersistent) would be a better way to go.

**Comment by davereid** [comment]
Yep, I realized the same once I saw the Composite driver! I'll wait for https://github.com/tedious/Stash/pull/234 to get resolved before submitting a PR for adding an isPersistent() method to all drivers.

**Comment by davereid** [comment]
@tedivm Do you have a preference if Drivers are marked as persistent by default or not? I'm guessing should probably return FALSE in AbstractDriver::isPersistent(), and only certain drivers return TRUE.

**Comment by tedivm** [comment]
Temp by default would be my preference- If bugs are make I'd rather have someone mark a persistent driver as temp than the other way around.

**Comment by davereid** [comment]
Yep, that was my first preference as well.
