### ISSUE TITLE
Proposal: implement PSR-6 cache standard

### ISSUE THREAD

**Issue by seyfer** [tedious/Stash#243]
https://github.com/php-fig/fig-standards/blob/master/proposed/cache-meta.md
https://github.com/php-fig/fig-standards/blob/master/proposed/cache.md

Would it be implemented when it will became accepted ?

**Comment by tedivm** [comment]
I'm one of the authors of that standard, so yes I plan on implementing it in Stash :-)

**Comment by seyfer** [comment]
Cool :-) :+1:

**Comment by Ninestein** [comment]
Nice!
:+1:

**Comment by tedivm** [comment]
If you want to test it out I have a full PSR6 compliant implementation over at #249. It does not yet directly implement the interfaces, as I don't want to do that on the main branch until things are settled with the FIGS but I am okay with merging these changes back if they look alright. 

There is also some cleanup to do, but my main priority was making it functional and writing unit tests (yes, this is fully tested).

**Comment by kzap** [comment]
+1

**Comment by tedivm** [comment]
Thanks @kzap, I really appreciate it.

**Comment by tedivm** [comment]
Also, you should all check out #253, which includes PSR-6 compliance.

**Comment by mablae** [comment]
FYI: PSR-6 is in voting phase now: 
https://groups.google.com/forum/#!topic/php-fig/dSw5IhpKJ1g

**Comment by tedivm** [comment]
Which raises a good point- anyone who wants to test out #253 should do so as soon as possible.

**Comment by tedivm** [comment]
Closing this issue out, as this has been completed in the dev branch.
