### ISSUE TITLE
Apple or Apples?

### ISSUE THREAD

**Issue by ctubio** [tedious/Stash#259]
as seen in examples at http://www.stashphp.com/:
```php
$item->set('apple');
// string(6) "apples"
```
(note that i copy/pasted from the website but removed all lines without interest for the issue)

EDIT: if you ask me, i preffer apple**s** cos then you have more sauce.

**Comment by liamja** [comment]
:+1:

**Comment by tedivm** [comment]
Issues for the documentation should be submitted on [it's github page](https://github.com/tedious/www.stashphp.com). That being said thank you for pointing it out!
