### ISSUE TITLE
Multiple pools

### ISSUE THREAD

**Issue by shopblocks** [tedious/Stash#262]
If you have multiple pools being setup, then you are in for a world of pain.

The way we had this setup was to have it created on our Abstract model as a static::$pool, which was absolutely fine, until we setup tests and had it created in the setUp method too.

These were both created using $pool = (new Cache())->pool;

This clears data out fine, when it is using its own instance, but in our tests, the instance in the model clears out data, and the instance in the test checks for this being cleared.

This doesn't pass the tests. It appears that the pool has some inmemory caching too, and when you re-open getItem, it will not have the latest data.

The fix for this is to have it implemented as a singleton. After we did this (and call Cache::getInstance()->pool instead, it seems to be absolutely fine.

Just a heads up for anyone else experiencing this issue, and perhaps it can be written into the documentation to make it clear that a single instance should be used at any one time.

**Comment by tedivm** [comment]
How are you setting the drivers for this pool? It sounds like you've got the Ephemeral driver in both of these pools (either stand alone or as part of the composite driver), but aren't using the same instance of the Ephemeral driver for each.
