### ISSUE TITLE
Stash\Driver\FileSystem creates default cache directory, regardless if a path is set 

### ISSUE THREAD

**Issue by yrizos** [tedious/Stash#263]
`Utilities::getBaseDirectory` gets called at the top of `FileSystem::setOptions` - see https://github.com/tedious/Stash/blob/master/src/Stash/Driver/FileSystem.php#L135. 

This means that the driver will always try to create the default cache directory, regardless of if a path has been set via `FileSystem::setOptions`.

This will (unnecessarily) fail if the user calling the script does not have permissions to `mkdir` in the system's temp directory (which is how I noticed the issue in the first place). 

This is only an issue with v0.13, up until v0.12.3 `Utilities::getBaseDirectory` was only called if (and only if) a cache path had not been set via `FileSystem::setOptions` (see https://github.com/tedious/Stash/blob/v0.12.3/src/Stash/Driver/FileSystem.php#L134).

**Comment by tedivm** [comment]
Thanks for reporting!

**Comment by reenl** [comment]
The problem persist when not using constructor injection, this is also the case for the symfony bundle:
https://github.com/tedious/TedivmStashBundle/blob/master/Factory/DriverFactory.php#L68

Not sure how to fix it, but I'd be happy to submit a PR.
