### ISSUE TITLE
FileSystem, size limit

### ISSUE THREAD

**Issue by Seanmcn** [tedious/Stash#269]
Been using the file cache on a popular large project and I'm noticing the size of the cache becomes pretty enormous, wishing I had the ability to limit its size rather than purging/clearing the cache periodically.

I'm thinking I could just edit the FileSystem driver to accept a option of 'memoryLimit' or something, then once that limit is hit it would just remove a few of the older entries. 

I'm going to be doing this anyway on my version, just wondering if this is something that other people are interested in and perhaps worth me making a pull request for?

**Comment by tedivm** [comment]
I'm a big fan of pull requests and encourage people not to fork the software unless there's a real need.

That being said I think you're going to find this to be more complicated than you're expecting, and I am going to be paying attention to performance. You may be at the point where putting a memcached instance up and using that would give you some real performance improvements.

**Comment by Seanmcn** [comment]
I'm also going to be attention to performance since I'm using Stash in production right now. I am using memcached, I'm using the composite driver in this order; APC -> Memcached -> FileSystem however Memcached is only around 4GB, FileSystem cache is around 40GB right now. I would just ideally like for the FileSystem cache to be a bit more intelligent on what it is caching, limiting it seems like a good idea. 

Anyway this is something I'll need to create a solution for in work so whenever I do figure out that solution I'll create a PR with my findings and solution. If it isn't something that fits Stash, I'll fork our own copy at that stage.

**Comment by tedivm** [comment]
Any updates?

**Comment by Seanmcn** [comment]
Well on the problem project I've basically removed a lot of stuff that I was caching to keep the File System size low and I'm also clearing it periodically. That has at least prevented the drive from just continuously filling but is pretty much a band-aid for the problem :laughing: However moving forward Stash is the caching library I want to keeping using for PHP work, so this is still something I'll be looking into a solution for, however I'm probably not going to get a chance to do anything on it until after the holidays.

**Comment by tedivm** [comment]
You should consider using two pools- one for things you want to make sure to cache, and another for those secondary things. Then you can turn the secondary things on when you want to, or just save them in a different backend (such as apc) to provide some speed improvements.
