### ISSUE TITLE
Retrieving data with stacks

### ISSUE THREAD

**Issue by bateszi** [tedious/Stash#271]
I'm attempting to use stacks to store multiple cache items with keys like `/my/users/123` and then get every item by using a key like `/my/users`. Having read the documentation, the examples provided talk about clearing items with a stack path as above, but is it possible to get all data from the cache in this way, too? I've had no luck so far, so thought I could be missing something (however, caching an array of objects without using stacks works wonderfully.)

**Comment by tedivm** [comment]
Unfortunately this isn't something that's supported. I have a policy with Stash of only exposing features that I can make work across all back ends, and with some of the drivers (such as memcached) this isn't really possible.

**Comment by bateszi** [comment]
Okay. Thanks anyway, this is a really cool library.
