### ISSUE TITLE
Cache is not hit when using precompute invalidation with an expiration time of less than 40 seconds

### ISSUE THREAD

**Issue by carolosf** [tedious/Stash#272]
If you are using the default invalidation precompute strategy and set a cache expiration that is less than 40 seconds the cache always misses even if it has not expired yet.

Please have a look at this test that illustrates the issue:
https://github.com/carolosf/Stash/blob/memcached-expiration-bug/tests/Stash/Test/ExpirationTest.php

I am not sure if this is the intended behaviour or not.

If it is intended behaviour the documentation should explain that when using the precompute strategy expiration times less than 40 seconds are not supported.

When using the Ephemeral driver this issue does not occur.

Since this has a different behaviour depending on which driver you use it may also be a Liskov substitution principle violation. 

The line that produces this result can be found in src/Stash/Item.php on line 503.

**Comment by tedivm** [comment]
The documentation has been updated on the new versions, just not pushed out yet. Keep in mind that the locking mechanism will still be in place, so even during the precompute phase only one request (regardless of how many requests you have) will be a miss, and the rest will continue to be hits up until they actually expire.

This should also not have any differences depending on drivers- the code that handles this is higher up in the chain, not in the drivers, so there is no reason why what driver you are using should affect anything. You may actually be encountering the locking feature from above during your testing.
