### ISSUE TITLE
Using file system cache and no path 

### ISSUE THREAD

**Issue by JonoB** [tedious/Stash#273]
For some reason, when reading from cache items, I am unable to use the `setOptions` method to initialise the cache path. Doing so causes the following errors:

```
mkdir(): Permission denien in /vendor/tedivm/stash/src/Stash/Utilities.php 111
mkdir(): Permission denied /vendor/tedivm/stash/src/Stash/Utilities.php 228
```

I eventually tracked this down to the following:

This does *not* work:
```
$path = getenv('CACHE_PATH');
$driver = new Stash\Driver\FileSystem();
$driver->setOptions(['path' => $path]);
$pool = new Stash\Pool($driver);
```

This works
```
$path = getenv('CACHE_PATH');
$driver = new Stash\Driver\FileSystem(['path' => $path]);
$pool = new Stash\Pool($driver);
```

Note that this only seems to be a problem when reading from cache, and not when writing.

**Comment by tedivm** [comment]
This is resolved in the v1.0.0 dev branch.
