### ISSUE TITLE
Documentation not clear on stacks

### ISSUE THREAD

**Issue by wizhippo** [tedious/Stash#278]
Under groupings it states `If the first character of the key is not a slash, Stacks behaves exactly like the standard Cache interfaces`.  Yet under the basic usage it shows
```
$item = $pool->getItem('path/to/data')
$item->clear(); // clears 'path/to/data/*' as well as 'path/to/data'
```

The example has no leading slash.  Is this correct or am I misunderstanding?

**Comment by ibrambe** [comment]
It doesn't matter if you add a leading slash or not, if you look in the source (0.14.1), leading and trailing slashes are trimmed:

```php
public function getItem($key)
{
    $keyString = trim($key, '/');
    ...
```

**Comment by wizhippo** [comment]
ok. do any key with slash ends up a stack.  thanks for pointing it out.
