### ISSUE TITLE
V1.0 Release Milestone

### ISSUE THREAD

**Issue by bubba-h57** [tedious/Stash#284]
We would like to begin using Stash in a production project. We see that the [FAQ states](http://www.stashphp.com/FAQ.html) that Version 1.0 will come out once [PSR-6](http://www.php-fig.org/psr/psr-6/) is complete, and it is now accepted. [243](https://github.com/tedious/Stash/issues/243) demonstrates that [v1.0.0-dev](https://github.com/tedious/stash/tree/v1.0.0-dev) has been available for about a month, and no significant [issues](https://github.com/tedious/Stash/issues) appear to be opened on it and no code changes have been committed in that month.

Could we get the [README.md](https://github.com/tedious/Stash/blob/master/README.md) updated with a target release date? And or update the [FAQ](http://www.stashphp.com/FAQ.html) with some expectations? I would love to have that to convince my team to begin working on  [PSR-6](http://www.php-fig.org/psr/psr-6/) [Stash](https://github.com/tedious/Stash)!

**Comment by tedivm** [comment]
I'll be updating things this weekend. We're launching a 0.14 branch as a release candidate for v1, and will let that run for awhile before making that final release. I don't expect there to be many changes between v0.14 and v1 though.

**Comment by bubba-h57** [comment]
Thanks! I'll be looking forward to the weekend.

**Comment by nilportugues** [comment]
Nice to know @tedivm

**Comment by ivarb** [comment]
+1

**Comment by jszobody** [comment]
@tedivm It's been about two weeks, not seeing a v0.14. Any update?

**Comment by V13Axel** [comment]
@tedivm would love to see some movement on this, excited to use this in production.

**Comment by ivarb** [comment]
Same :)

**Comment by tedivm** [comment]
I just finished the documentation updates and pushed them live. I am waiting on Travis-CI to confirm the master branch here is good after small small changes, and then I'll push live (probably in the next 15 minutes).

**Comment by tedivm** [comment]
I apologize for the delays, but I've been sick for the last week :-(

**Comment by tedivm** [comment]
Released!

**Comment by ivarb** [comment]
No problem! Thank you very much :+1:
