### ISSUE TITLE
Not saving cache

### ISSUE THREAD

**Issue by vatnoise** [tedious/Stash#287]
Trying this on a localhost at the moment, gave the folder all the permissions.

When I do $item->lock(); it creates a folder structure and a temporary file (I guess for locking purposes) and then removes it. And that's all ... it doesn't seem to create the actual cache file (I guess I might be doing something wrong?).

Here's my code:

```
// ... loading Stash library files manually ...
$driver = new Stash\Driver\FileSystem(['path' => $_SERVER['DOCUMENT_ROOT'].'/admin/tmp/']);
// $driver->setOptions(array()); // not using this because it gives an error

$pool = new Stash\Pool($driver);
$id = 'SUPERBIGFILE123';

$item = $pool->getItem('/admin/tmp/' . $id);
// also tried:
// $item = $pool->getItem($_SERVER['DOCUMENT_ROOT'].'/admin/tmp/' . $id);
// $item = $pool->getItem($id);
$data = $item->get();

if($item->isMiss())
{
    $item->lock();
    $data = 'hello';
    $item->set($data);
    // also tried:
    // $item->set($data, 3600);
}
```

**Comment by tedivm** [comment]
Are you working against dev-master or a specific version?

**Comment by ChadSikorra** [comment]
Don't you have to do `$pool->save($item->set($data));` now? This caught me a little off guard recently. Prior to the more recent versions simply doing `$item->set($data);` without the call to `save()` on the pool was sufficient to cache an item.

**Comment by tedivm** [comment]
This is due to how PSR-6 was designed. The idea is that the Pool is a repository that you save and pull items from. There was no way to make "set" save while still following PSR-6, so I pushed on the side of compatibility.

**Comment by vatnoise** [comment]
Adding $pool->save($item); worked!!!

That's strange, I'm trying to find on the website the place where I got the code from and it mentions ->save() everywhere I look now. I guess I was ->save()-blind yesterday. :/

**Comment by tedivm** [comment]
@vatnoise - the website updates were literally pushed yesterday with the new version. This is one of the changes in the v0.14.0 line of code to make it compatible with PSR6.

You weren't blind, you were just ahead of the game :-)
