### ISSUE TITLE
Consider tagging 1.0.0 and adopting SemVer

### ISSUE THREAD

**Issue by mrclay** [tedious/Stash#289]
After 4 years, a bunch of dependent projects, and 300K+ installs via packagist, isn't it time Stash goes 1.0?

As Elgg was requiring "~0.12", the PSR-6 BC break in 0.14 bit us. Adopting SemVer would prevent this kind of thing.

**Comment by tedivm** [comment]
@mrclay -

The original plan was for this to be v1, however the number of changed made were more than I was comfortable adding into a v1 release without having some extended testing and usage. After some discussion with other stakeholders it was decided that v0.14 would act as a release candidate line for v1.0.0.

Sorry you guys had trouble. However,  semver allows for [pre-v1 development](http://semver.org/#how-should-i-deal-with-revisions-in-the-0yz-initial-development-phase), with increments in the Minor version signifying backwards incompatible changes. We are following semver, and have documented this on our [readme](https://github.com/tedious/Stash#composer) and [website](http://www.stashphp.com/Overview.html#composer).

I am sorry about the inconvenience, but this should be the last time you have to deal with it. I will be releasing this as v1.0.0 after a couple of months with the new API.


PS: Stash was launched in 2009, so this makes seven years of development :-)

**Comment by mrclay** [comment]
Yeah, using `~` with a 0.x release was our bad. Can we assume `0.14.*` will be safe from BC breaks?

**Comment by tedivm** [comment]
Absolutely. There are never any BC breaks in patch releases.
