### ISSUE TITLE
Why setOptions() now protected?

### ISSUE THREAD

**Issue by Balancer** [tedious/Stash#290]
How can I set options in new version?

Why in documentation example with incorrect use setOptions()?
```php
$options = array('path' => '/tmp/myCache/');
$driver->setOptions($options);
```

It don't work with 
```
PHP Fatal error:  Call to protected method Stash\Driver\Redis::setOptions()
```

**Comment by tedivm** [comment]
Options go to the constructor instead of setOptions.

So -
```php
new \Stash\Driver\Redis(array('path' => '/tmp/myCache/'));
```

This was because we had previously supported both and this caused some issues.

**Comment by Balancer** [comment]
Ok, thanks.
