### ISSUE TITLE
Plans for semver?

### ISSUE THREAD

**Issue by juho-jaakkola** [tedious/Stash#291]
A project that I work with got bitten by the non-BC changes mentioned in issue #287.

This shouldn't really had come as a surprise because Stash's README file clearly states:

> Until Stash reaches a stable API with version 1.0 it is recommended that you review changes before Minor updates

Does this mean Stash will start conforming to [semver](http://semver.org/) once version `1.0.0` comes out?

**Comment by scaytrase** [comment]
`0.x.y` [conforms semver](http://semver.org/#doesnt-this-discourage-rapid-development-and-fast-iteration) totally and means that there is no stable api yet. So README note is just a reminder
