### ISSUE TITLE
Fatal error: Interface 'Psr\Cache\CacheItemPoolInterface' not found

### ISSUE THREAD

**Issue by KiritsuguKun** [tedious/Stash#297]
Is the documentation completely outdated?
If I try to include stash, this will shown up:

**Fatal error: Interface 'Psr\Cache\CacheItemPoolInterface' not found**

`include_once ('./autoload.php');`
`$driver = new Stash\Driver\Sqlite(array('path' => './cache/'));`
`$cache = new Stash\Pool($driver);`

**Comment by tedivm** [comment]
The newest version of Stash requires the PSR-6 interfaces. If you are loading this library by itself then you should also load those classes. I highly recommend using Composer to take care of this instead.

**Comment by KiritsuguKun** [comment]
Ah okay, thank you, now it works.
I used Stash several months ago and I just tried the same way to implement this as I thought it should work. Thank you for your help.
