### ISSUE TITLE
How to prevent keys collision while using Memchached driver?

### ISSUE THREAD

**Issue by FinesseRus** [tedious/Stash#300]
I've failed to find the answer in the documentation.

As we know, Memcached has common key namespace for each client. This feature causes keys collisions when multiple web applications use the same Memcached server.

Do I have to perform any explicit actions to prevent collisions? Is the `\Stash\Pool::getItem` method abstracted from this problem?

**Comment by tedivm** [comment]
When setting up the Memcached driver you can pass options in to the underlying system. The OPT_PREFIX_KEY option will let you specify a key that will essentially namespace things.

**Comment by FinesseRus** [comment]
@tedivm Does `Pool::setNamespace` do the same thing (namespaces things)? Which one if preferable: `OPT_PREFIX_KEY ` or `Pool::setNamespace`?

As I understand, Stash doesn't separate namespaces for each application allowing them to have common cache. Separating namespaces is option for developers. Do I understand correctly?

**Comment by tedivm** [comment]
The built in namespaces are meant to segment different areas of the same application from each other, but not to separate different applications on the same backend. It won't work that way, as the driver also stores meta data that isn't going to be uniquely namespaced.

I think the OPT_PREFIX_KEY would make the most sense. A unique prefix key for every application will prevent any mingling of data.

**Comment by FinesseRus** [comment]
@tedivm I got it. Thank you!

**Comment by tedivm** [comment]
No problem, I'm happy to help!
