### ISSUE TITLE
Persistent connect for memcached?

### ISSUE THREAD

**Issue by dpashin** [tedious/Stash#313]
I use "tedivm/stash": "0.13.2".
Stash\Driver\Memcached::_construct constructs \Memcached instance, but there is no ability to pass $persistent_id parameter there.
Then we add servers, but there is also no way to pass $persistent_id there:
line 66:

```
        $memcached = new \Memcached();

        $serverList = $memcached->getServerList();
        if (empty($serverList)) {
            $memcached->addServers($servers);
        }

```

How can i use persistent connection with memcached driver?

**Comment by alexbowers** [comment]
Is this still an issue on the latest version?

**Comment by dpashin** [comment]
@alexbowers, sorry, i have no time to check. feel free to close issue, if you want
