### ISSUE TITLE
Allow multiple redis servers in config

### ISSUE THREAD

**Issue by alexbowers** [tedious/Stash#324]

**Comment by neok** [comment]
@alexbowers i guess it's already supported, see - https://github.com/tedious/Stash/blob/master/src/Stash/Driver/Redis.php#L52

**Comment by alexbowers** [comment]
This comment seems to suggest otherwise: https://github.com/tedious/Stash/blob/master/src/Stash/Driver/Redis.php#L108

I'll be looking into this more over the coming weeks, as I have a mostly-complete way for read write splitting for redis servers, and that will probably include multiple server since it fits there quite well. Just currently trying to make it 100% backwards compatible

**Comment by tedivm** [comment]
If it's not 100% backwards compatible it's not the end of the world as the next release is going to break BC slightly anyways.

**Comment by alexbowers** [comment]
I should hopefully find out over this weekend if i get the chance. I believe it can be made 100% fully BC.

**Comment by alexbowers** [comment]
Totally forgot about this. Will submit a PR soon.

**Comment by tedivm** [comment]
@alexbowers - let me know what's up. Multiple servers should be supported as is- the test suite even runs a second server to test again. It's possible the comment you're referencing is an older one that should just be erased.
