### ISSUE TITLE
Stash\Item->get() does not follow PSR-6 standard

### ISSUE THREAD

**Issue by bshaffer** [tedious/Stash#327]
The method `Stash\Item::get` should return `null` if `Stash\Item::isHit()` returns false, according to [PSR-6](http://www.php-fig.org/psr/psr-6/):

``` php
    /**
     * Retrieves the value of the item from the cache associated with this object's key.
     *
     * The value returned must be identical to the value originally stored by set().
     *
     * If isHit() returns false, this method MUST return null. Note that null
     * is a legitimate cached value, so the isHit() method SHOULD be used to
     * differentiate between "null value was found" and "no value was found."
     *
     * @return mixed
     *   The value corresponding to this cache item's key, or null if not found.
     */
    public function get();
```

This is causing issues in implementations for multiple cache interfaces. Fixing this issue causes multiple tests to fail, namely [this test](https://github.com/tedious/Stash/blob/master/tests/Stash/Test/AbstractItemTest.php#L194) which asserts something directly contrary to the PSR-6 specification. The test asserts the control stash is a miss, but also the old value is returned:

``` php
$runningStash = $this->testConstruct($key);
$runningStash->set($oldValue)->expiresAfter(-300)->save();

// Test without stampede
$controlStash = $this->testConstruct($key);
$controlStash->setInvalidationMethod(Invalidation::VALUE, $newValue);
$return = $controlStash->get();
$this->assertEquals($oldValue, $return, 'Old value is returned');
$this->assertTrue($controlStash->isMiss());
```

I will submit a PR to fix this! As it's a BC breaking change, I am anticipating some justification for this behavior, although I strongly recommend changing it. It is causing errors https://github.com/google/google-api-php-client/issues/1075 and https://github.com/google/google-api-php-client/issues/1071.

**Comment by tedivm** [comment]
Closed with accepted merge request. Will be pushed out as part of Stash 0.15, since this is a BC breaking change.

**Comment by bshaffer** [comment]
@tedivm When can we expect `0.15` to be tagged?

**Comment by tedivm** [comment]
I"m going to leave that up to @alexbowers, as he's working on a redis change that may also break BC.

**Comment by alexbowers** [comment]
I plan on finishing work on my feature this weekend so hopefully next week
we can tag it. What's involved in a release? Is it just new tag on here?

**Comment by alexbowers** [comment]
I'm not going to be able to do this work for a little while I don't think. I have a mostly working implementation, but i'm not 100% happy with it. Do you want to just create a tag @tedivm ?

There is currently a master branch failing, but I am unsure as to why, since the PR was passing perfectly well.

**Comment by bshaffer** [comment]
+1 to tagging a `0.15` now and making the redis change `0.16`.

**Comment by alexbowers** [comment]
This evening i'll be able to probably find an hour to try to fix the failing tests in master. If I fail can I get some assistance @bshaffer or @tedivm ?

**Comment by alexbowers** [comment]
I have pulled it all locally, and tested it against php56 and php7 on a mac, Unfortunately, I cannot replicate the issue (possibly because of the number of skipped tests)

@bshaffer Are you able to replicate the failing tests at all?

**Comment by bshaffer** [comment]
What is the word on tagging a new release? This change has been merged for over a month now.

**Comment by tedivm** [comment]
A new release has been tagged some I'm closing this.
