### ISSUE TITLE
Writing cache entries in JSON format

### ISSUE THREAD

**Issue by fetzi** [tedious/Stash#332]
I'm currently working on a project using stash. I have the challenge to warm up the cache with a node.js service.

After porting the cache key magic to javascript I realized that each cache entry is written as a PHP array.

My suggestion would be to write the whole cache entry in JSON format. Each stored item must contain either a JSON string or an object extending `JsonSerializable`. The stash specific infos (create timestamp, expires on) should not be the problem to port.

If the cache item data is not in a JSON serializable format an Exception should be thrown.

I know that this feature is only useful for a minority of stash users, so I would recommend to add it as an opt in feature in the general cache configuration.

Please let me know what you think about this feature. If the idea gets accepted, I would be able to provide an PR containing this functionality.

**Comment by alexbowers** [comment]
`unserialize()` is implemented in JS.

You can use it from here:

http://locutus.io/php/var/unserialize/

As for the system changing, it would be a huge breaking change, so is unlikely to happen anytime soon.

**Comment by alexbowers** [comment]
And likewise, there is also a `serialize` method: http://locutus.io/php/var/serialize/
