### ISSUE TITLE
public method in doc is protected in sources

### ISSUE THREAD

**Issue by gsouf** [tedious/Stash#337]
Checking the redis driver documentation the method ``AbsctractDriver::setOptions`` is public (http://www.stashphp.com/Drivers.html#redis) but in the sources it's protected (https://github.com/tedious/Stash/blob/v0.14.1/src/Stash/Driver/AbstractDriver.php#L53)

Looks like the good method to set options is through the constructor, isn't it ?

**Comment by alexbowers** [comment]
I think this was changed to match PSR6

**Comment by alexbowers** [comment]
They should be set in the constructor

**Comment by gsouf** [comment]
Ok, I will PR in the doc

**Comment by alexbowers** [comment]
Thanks

**Comment by alexbowers** [comment]
Please #link it here when its done, and i'll review

**Comment by gsouf** [comment]
Well, that was already partially fixed by tedious/www.stashphp.com#12 but the website is not up to date

**Comment by alexbowers** [comment]
Hmm, I'm afraid I don't have control of the website. I'll ping @tedivm to update the website
