### ISSUE TITLE
0.14.2 release from master?

### ISSUE THREAD

**Issue by andrerom** [tedious/Stash#338]
Looking over master it seems to be mainly bug fixes and minor improvements at this point.

Do you consider this for 0.14.2 or should the interface changes that are added to reflect the implementation be exlusive for 0.15?
ref: https://github.com/tedious/Stash/compare/v0.14.1...master

Note: For 0.14.2 I'll also need #336, as the bundle PR got merged and tagged already in v0.6.2 _(no links between them so overlooked the relation)_.

**Comment by tedivm** [comment]
I can see the argument made either way. I don't really see much else coming through the pipeline so maybe we should tag this as 0.14.2, give a month or two of testing, and tag it v1.0.

**Comment by andrerom** [comment]
For v0.14.2 if we can merge #336 it will be ready for tag so 👍 

For 1.0 there are a few more things I can see from my side:
- #327, aka any changes to conform with spec
- Predis support, or solve issue with php-redis as we have several reports of instability of the Stash + php-redis combination under load, and same people reported custom driver with Predis solved the issue.

With those changes there can be a v1.0.0-rc1 form my pov.

**Comment by alexbowers** [comment]
#336 has been merged now.

I have also made a `1.0` milestone with some requirements in my opinion.

Things like test stability.

**Comment by alexbowers** [comment]
I'll leave the actual tagging to @tedivm

**Comment by andrerom** [comment]
Cool, looking forward to it :)

**Comment by XedinUnknown** [comment]
Hi,

This is NOT a BC breaking change, because the documentation claims compatibility with PSR-6, making #327 a bug, not a part of the interface. Therefore, 0.14.2 is an appropriate version. 

Please do not release 1.0 until PSR incompatibilities, such as #349, are fixed.

**Comment by tedivm** [comment]
Release has been released.

**Comment by andrerom** [comment]
Nice, but any reason why the PHP 7.2 fix was left out of it? _(not a problem right now, but it will become one eventually when it's out)_
