### ISSUE TITLE
Documentation: Clear a key with subkeys wrong example code

### ISSUE THREAD

**Issue by tstrijdhorst** [tedious/Stash#345]
http://www.stashphp.com/Basics.html#clearing-data

It seems to me the second example should be:
```php
// Clearing a key with subkeys
$pool->deleteItem('path/to/data');  // clears 'path/to/data/*' as well as 'path/to/data'
```

If not I obviously don't get how it works so I might be extra stupid or some explanation would be nice :)

**Comment by alexbowers** [comment]
It looks like you are correct; however this has already been fixed.

As you can see on the master branch https://github.com/tedious/www.stashphp.com/blob/master/Basics.rst it is correct.

@tedivm Please can we get the website updated?
