### ISSUE TITLE
Keys Incompatible With PSR-6 and PSR-16

### ISSUE THREAD

**Issue by XedinUnknown** [tedious/Stash#349]
The [grouping](http://www.stashphp.com/Grouping.html) docs state that hierarchy is possible by separating nesting levels with `/`. This is incompatible with [PSR-6](http://www.php-fig.org/psr/psr-6/#definitions) and [PSR-16](http://www.php-fig.org/psr/psr-16/#definitions), which both explicitly prohibit that:
>The following characters are reserved for future extensions and MUST NOT be supported by implementing libraries: `{}()/\@:`.

**Comment by tedivm** [comment]
Compatibility can be maintained by simply not using the feature.

**Comment by XedinUnknown** [comment]
Yes, that means that the keys *I use* in my software may be compatible, but your software is not compatible. *MUST NOT be supported* is very clear, and doesn't leave it up to interpretation, IMHO.
