### ISSUE TITLE
Random critical error

### ISSUE THREAD

**Issue by rashidul0405** [tedious/Stash#360]
This is the error we got time to time. No specific use case. For example, while editing article we got this time to time, but most of the time it works.

from log:
--------------

> request.CRITICAL: Uncaught PHP Exception UnexpectedValueException: "RecursiveDirectoryIterator::__construct(/volumes/friflyt/ezpublish5/ezpublish/cache/prod/stash/0fea6a13c52b4d47/25368f24b045ca84/c21f969b5f03d33d/43e04f8f136e7682/4a1c6be177996f9e/03934ae1c1c02ffc/c1ea7b5cb5837487/95f67f2e772f6043/59cd7b3222254010): failed to open dir: No such file or directory" at /volumes/friflyt/ezpublish5/vendor/tedivm/stash/src/Stash/Utilities.php line 144 {"exception":"[object] (UnexpectedValueException(code: 0): RecursiveDirectoryIterator::__construct(/volumes/friflyt/ezpublish5/ezpublish/cache/prod/stash/0fea6a13c52b4d47/25368f24b045ca84/c21f969b5f03d33d/43e04f8f136e7682/4a1c6be177996f9e/03934ae1c1c02ffc/c1ea7b5cb5837487/95f67f2e772f6043/59cd7b3222254010): failed to open dir: No such file or directory at /volumes/friflyt/ezpublish5/vendor/tedivm/stash/src/Stash/Utilities.php:144)"} []

Environment:
--------------------
Symfony.

Stash settings:
--------------------
```stash:
    caches:
        default:
            drivers:
                - FileSystem
            inMemory: true
            registerDoctrineAdapter: false
```

**Comment by tedivm** [comment]
This is due to a race condition where one request deletes the directory while another is also deleting it. It tends not to happen until a site gets busier, and honestly at that point you should really switch to the sqlite driver for local caching.

**Comment by rashidul0405** [comment]
@tedivm Thank you very much for your answer. I assume so. I'm confirming that we've quite a busy site with lots of contents. Will test sqlite driver later on.
