### ISSUE TITLE
Project abandoned? 

### ISSUE THREAD

**Issue by theluk** [tedious/Stash#361]
I see questions not being answered for a while and also Pull Requests being completely ignored. Is this project abandoned? 

if so, maybe adding or changing maintainers would help, otherwise only forks will happen with endless solutions.

**Comment by tedivm** [comment]
It's not abandoned, and I have added other maintainers to it (for example, @alexbowers has full write access to the project). 

I'm willing to add more people on if they want to help out with the project.
