### ISSUE TITLE
Fatal error when clearing APCu cache on cli

### ISSUE THREAD

**Issue by Biont** [tedious/Stash#365]
# How to reproduce
1. Enable and configure apcu
2. Verify that apc is not running on CLI (`apc.enable_cli=0`) as will be default on many installations
3.  `Stash\Driver\Apc->clear();`

Stash will throw the following error:

`APC must be enabled to use APCuIterator`, thrown from [here](https://github.com/krakjoe/apcu/blob/2a3efe97e8765063d8c20b4b42ef8df34a708475/apc_iterator.c#L293)

I guess this is because the extension/php lib is technically loaded, but not enabled for the current process. Therefore, `Stash\Driver\Apc->isAvailable()` won't complain since it merely checks for the existence of apc* functions.

**Comment by alexbowers** [comment]
Is using `ini_get('apc.enable_cli')` suitable enough to check this?

**Comment by tedivm** [comment]
It looks like this is a change in behavior from the APC/APCu side of things- originally if it wasn't enabled the functions wouldn't exist, now they exist but throw an error.

This is probably the appropriate response though- it *is* an error to try and use this functions when they aren't enabled. If we were to suppress the error on the Stash side of things people would end up with stale caches without realizing it. Failing loudly is probably the best thing to do here.

**Comment by Biont** [comment]
> Failing loudly is probably the best thing to do here.

I disagree, mostly because of the "here" detail. If it should fail loudly, it should do so earlier `Apc->isAvailable()` exists for this reason and a 
```php
if ( PHP_SAPI === 'cli' && ! ini_get( 'apc.enable_cli' ) ) {
   return false;
}
```
as suggested by @alexbowers might be enough to steer around this problem (don't quote me on this, it'd just be my quick workaround) . 

Wouldn't you expect `Apc->isAvailable()` to tell you that the driver (and caching backend) is ready to use? In this case, it _passes this check_, and _still_ blows up later. Keep in mind that it is **only** throwing an error if `Apc->clear()` is called **with a $key parameter**. All other methods will work as expected (albeit assumedly silently failing on the apcu_* functions). So if you rarely use group invalidation (which I think is what is supposed to happen here), you would not even realize there is a problem.

You could say that `APCuIterator` is the only one brave enough to go ahead and complain here, while the `apcu_*` functions just sit there twisting their thumbs. In any case, it seems to me like `Apc->isAvailable()` should return `false` if you're on cli and apcu is not enabled on cli.

**Comment by alexbowers** [comment]
This seems like an appropriate fix.

Are you able to PR it @Biont ?
