### ISSUE TITLE
Driver Memcache "clear" = "inc" ?

### ISSUE THREAD

**Issue by franck-grenier** [tedious/Stash#369]
Hello,
when I look at your memcache driver, I can see that your "clear" function finally does an "increment" when passed a `$key` => https://github.com/tedious/Stash/blob/master/src/Stash/Driver/Memcache.php#L170

Is it normal ?
I mean that when I call a "clear" function on a `$key`, I'm expecting to remove that item from cache, not increment its value (which is not systematically numeric).

At first sight, it looks like a bug to me. Shouldn't it be a `delete` call here ?

Or there is something I do not understand.

The problem for me is that my Memcached total items number is in constant growth.

**Comment by orcinus** [comment]
If i'm not mistaken, it increments *the path key*, not the value of the stored item.
Which invalidates it, as now Stash won't be able to access the stored value anymore.

If i'm understanding things correctly, when you store a value, Stash will:
- create a key with the path, and an md5 digest as the value
- then store your item with that md5 as its key

The clear method increments the md5 digest, making the stored item inaccessible. Memcached will eventually evict it, as no one will access it anymore from that point onwards.

As to why it doesn't simply use delete - i assume it has something to do with path support and making the children of a path inaccessible too.

**Comment by tedivm** [comment]
> As to why it doesn't simply use delete - i assume it has something to do with path support and making the children of a path inaccessible too.

Exactly.
