### ISSUE TITLE
Redis items aren't really deleted?

### ISSUE THREAD

**Issue by walterdl** [tedious/Stash#382]
Hi there,

I've noticed that items stored using Redis driver aren't never really deleted. Their values keep in database and a new key is created with an autoincrement, but when you get the value of the supposed deleted item is null. Example:

```
  // here just create an item
  // init driver and pool
  $driver = new Stash\Driver\Redis();
  $pool = new Stash\Pool($driver);

  // create an item
  $toCreate = $pool->getItem('/foo/bar');
  $toCreate->set('hello there');
  $toCreate->save();

  // the value is showed, everything fine until here
  echo $toCreate->get();
```

```
  // in other request ...
  // here delete the item
  $pool->deleteItem('/foo/bar');

  // get the item
  $deletedItem = $pool->getItem('/foo/bar');

  // this is null
  echo $deletedItem->get();
```

Using a client with GUI you can see that the item never is deleted, instead a new key is created with an autoincrement and every time that you try to delete the item this integer value becomes higher.

This is a normal behavior? With this the database never is cleared!

Redis version: 3.0.504
Stash version: v0.14.1
php version: 5.6

**Comment by tedivm** [comment]
This is expected behavior- the older items will expire out of the cache.
