### ISSUE TITLE
How to disable stashcache throughout project

### ISSUE THREAD

**Issue by mohit5540** [tedious/Stash#383]
Hello guys,

We are using Stashcach bundle for Symfony2 project. It is very useful for caching. 

We have changed our production server mysql database. Currently problem we are facing is, even after changing database configuration, application updates data in older database. This seems issue due to caching of doctrine object by stashcache. So if there is any way that we can disable stashcache throughout the project, it wont cache doctrine object.

Can anyone help in this regard.

Thanks

**Comment by tedivm** [comment]
Set the global variable `STASH_DISABLE_CACHE` to true.
