### ISSUE TITLE
Filedriver cannot save the cache with expiration time of less than 40 seconds

### ISSUE THREAD

**Issue by konorlevich** [tedious/Stash#385]
### PHP version:

> PHP 7.3.3-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Mar  7 2019 20:31:49) ( NTS )
> Copyright (c) 1997-2018 The PHP Group
> Zend Engine v3.3.3, Copyright (c) 1998-2018 Zend Technologies
>     with Zend OPcache v7.3.3-1+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
>     with Xdebug v2.7.0, Copyright (c) 2002-2019, by Derick Rethans

tedivm/stash version: v0.14.2

### Steps to reproduce

```php
$result = [
    'hitted' => 0,
    'missed' => 0,
    'missedExpiration' => [],
    'hittedExpiration' => [],
];
$i = 100000;
while ($i-- > 0) {
    $cacheKey = hash('sha256', 'some string');
    $data = ['key1' => 1, 'key2' => 2];
    $expiresIn = mt_rand(1, 100);
    $pool = new Stash\Pool(new \Stash\Driver\FileSystem);
    $pool->purge();
    $cacheItem = $pool->getItem($cacheKey)
        ->set($data)
        ->expiresAt(new \DateTime('@' . (time() + $expiresIn)));

    $saved = $pool->save($cacheItem);
    $hasItem = $pool->getItem($cacheKey)->isHit();
    if ($hasItem) {
        $result['hitted']++;
        $result['hittedExpiration'][] = $expiresIn;
        continue;
    }
    $result['missed']++;
    $result['missedExpiration'][] = $expiresIn;
}
var_dump([
    'hitted' => $result['hitted'],
    'missed' => $result['missed'],
    'averageMissedExpiration' => array_sum($result['missedExpiration']) / count($result['missedExpiration']),
    'averageHittedExpiration' => array_sum($result['hittedExpiration']) / count($result['hittedExpiration']),
    'missedLimits' => ['min' => min($result['missedExpiration']), 'max' => max($result['missedExpiration'])],
    'hittedLimits' => ['min' => min($result['hittedExpiration']), 'max' => max($result['hittedExpiration'])]
]);
```
### Expected behavior
'hitted' about 90-100%

### Real life

hitted : 545
missed : 455
averageMissedExpiration : 21.81098901098901
averageHittedExpiration : 72.22935779816514
missedLimits : array (
  'min' => 1,
  'max' => 47,
)
hittedLimits : array (
  'min' => 41,
  'max' => 100,
)

**Comment by tedivm** [comment]
You can change this behavior by setting the `precompute_time` to a lower value. The `precompute_time` is subtracted from the actual expiration, and when that new time is hit the chances of an cache miss are artificially increased so that the value can be regenerated before the expiration time- this distributes cache misses over time and prevents an expiration from causing every request from regenerating the data.
