### ISSUE TITLE
Filedriver purge didn't work in docker

### ISSUE THREAD

**Issue by konorlevich** [tedious/Stash#386]
###PHP version

> PHP 7.3.3-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Mar  7 2019 20:31:49) ( NTS )
> Copyright (c) 1997-2018 The PHP Group
> Zend Engine v3.3.3, Copyright (c) 1998-2018 Zend Technologies
>     with Zend OPcache v7.3.3-1+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
>     with Xdebug v2.7.0, Copyright (c) 2002-2019, by Derick Rethans

tedivm/stash version: v0.14.2

### Steps to reproduce
```php
$result = [
    'hittedAfterPurge' => 0,
    'hitted' => 0,
    'missed' => 0,
];
$i = 1000;
while ($i-- > 0) {
    $expiresIn = mt_rand(40, 1000);
    $cacheKey = hash('sha256', 'some string' . $expiresIn);
    $data = ['key1' => 1, 'key2' => 2];
    $pool = new Stash\Pool(new \Stash\Driver\FileSystem);
    $pool->purge();
    if ($pool->hasItem($cacheKey)) {
        $result['hittedAfterPurge']++;
    }
    $cacheItem = $pool->getItem($cacheKey)
        ->set($data)
        ->expiresAt(new \DateTime('@' . (time() + $expiresIn)));

    $saved = $pool->save($cacheItem);
    $hasItem = $pool->hasItem($cacheKey);
    if ($hasItem) {
        $result['hitted']++;
        continue;
    }
    $result['missed']++;
}
foreach ([
             'hittedAfterPurge' => $result['hittedAfterPurge'],
             'hitted' => $result['hitted'],
             'missed' => $result['missed'],
         ] as $key => $value) {
    echo $key, ' : ', var_export($value), PHP_EOL;
}
```

### Result
hittedAfterPurge : 351
hitted : 991
missed : 9

**Comment by tedivm** [comment]
`Purge` doesn't erase items from the cache, it simply cleans up items from the filesystem that have already expired (for some backends this happens automatically and purge doesn't do anything at all).

If you want to remove everything from the cache you need to run `clear` instead of `purge`.

**Comment by konorlevich** [comment]
> mom said i'm special (с)
Thanks
