### ISSUE TITLE
Function Redis::delete() is deprecated

### ISSUE THREAD

**Issue by jeabakker** [tedious/Stash#392]
found in
https://github.com/tedious/Stash/blob/8f1d28c765b257b05e932c28ad75c809e34fe12c/src/Stash/Driver/Redis.php#L219

see https://github.com/phpredis/phpredis/blob/148bf373b7a0d276f6f6fd1ec1e6b9407fba6497/README.markdown#del-delete-unlink

**Comment by saschanos** [comment]
@tedivm, is there any news? Would be great to enable someone to add a new version to the project :).

**Comment by saschanos** [comment]
For all others experiencing the same problem:
Update your composer requirement for now (branch contains master + fix).

```
composer require tedivm/stash dev-redis_del
```

**Comment by saschanos** [comment]
@tedivm, is there any news? Would be great to enable someone to add a new version to the project :).

**Comment by saschanos** [comment]
@tedivm, would it be possible for you to merge this?

**Comment by saschanos** [comment]
@tedivm, any news about this?
