### ISSUE TITLE
PHP 8.0 support

### ISSUE THREAD

**Issue by kordianbruck** [tedious/Stash#398]
PHP 8.0 has been released: https://www.php.net/releases/8.0/en.php

Please add support and/or configure your composer file to pass the checks.

**Comment by tomkyle** [comment]
As of Stash v0.16, any PHP 8-based project can consume Stash. Developers will, however, still not be able to develop locally since `composer install` fails due to version constraints coming with PhpUnit 6. I allowed myself to add a PR – see #400
