### ISSUE TITLE
Enhance PHP 8 compatibility 

### ISSUE THREAD

**Issue by joschahenningsen** [tedious/Stash#401]
We're getting this warning:

> Deprecated: Required parameter $permissions follows optional parameter $path in /var/www/html/vendor/tedivm/stash/src/Stash/Utilities.php on line 212

Could you please update such functions to conform with PHP8s standards?

https://github.com/tedious/Stash/blob/e155ca9e59bb36eec9f8c1f06d132dcb110cb45f/src/Stash/Utilities.php#L212

Thanks a lot!

**Comment by mateuszdebinski** [comment]
I think we can close this because changes were merged to master: https://github.com/tedious/Stash/pull/404

**Comment by joschahenningsen** [comment]
Yes, looks good. Thanks!
