### ISSUE TITLE
Query wildcard syntax?

### ISSUE THREAD

**Issue by barchard** [tedious/Stash#418]
Is it possible to query all items using `getItems`? Stash has [Stacks](https://www.stashphp.com/Grouping.html#stacks). Can these be used to query all items starting with a specific key? For instance, if you had multiple items stored with keys:

```
$friend1 = '/Users/Bob/Friends/Joe';
$friend2 = '/Users/Bob/Friends/Jane';
```

Then if you call:

```
$items = $pool->getItems(['/Users/Bob/Friends/']);
```

it would return `$friend1` and `$friend2`. Is this possible?

**Comment by tedivm** [comment]
It is not possible- the performance hit would be really bad if we wanted to add this functionality.
