### ISSUE TITLE
Update psr/cache to v3.0.0

### ISSUE THREAD

**Issue by brutto** [tedious/Stash#420]
I have project with php 8.1 and use 8.1 compatible libraries.  Can you up dependency version of `psr/cache` to ^3 (https://github.com/php-fig/cache/tags)? As i saw there is only 8.1 strict compatible changes.

**Comment by tedivm** [comment]
Looks like updating the dependency isn't enough to make this work- I'll have to take a more in depth look at this and update types elsewhere to bring them in line. The timing is good anyways, it may be time to drop some older php versions.

**Comment by tedivm** [comment]
I got slammed with some personal stuff (I bought a house! which it turns out is super time consuming!), but if you wanted to pick up #421 and get the tests passing I'd be happy to merge it and release.
